# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Solovan' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "CollectionViewWaterfallLayout"
  pod "TTGSnackbar"
  pod 'lottie-ios'
  pod 'Alamofire'
  pod 'SwiftVideoGenerator'
  pod 'Kingfisher', '~> 7.0'
  # Pods for Solovan
  
  pod 'NVActivityIndicatorView'
  pod 'AppLovinSDK'
  pod 'AppLovinMediationAdColonyAdapter'
  pod 'AppLovinMediationGoogleAdapter', '~> 11.5.0'
  pod 'AppLovinMediationIronSourceAdapter', '~> 8.0.0'
  pod 'AppLovinMediationVungleAdapter'
  pod 'AppLovinMediationUnityAdsAdapter'
  
  pod 'SwiftSoup'
  pod 'Zip'
  pod 'CryptoSwift'
  pod 'SideMenu'
  pod 'SDWebImage'
  pod 'CRRefresh'
  
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
